version: "3.1"
services:
  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - 8001:1234
    environment:
      - HOST=0.0.0.0
      - DB=${MONGODB_URI_DOCKER}
    networks:
      - backend

networks:
  backend:
    driver: bridge
