version: "3.1"
services:
  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - 8001:1234
    environment:
      - HOST=0.0.0.0
      - DB=mongodb://root:secret@mongo:27017/develop?authSource=admin
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=develop
    ports:
      - 27017:27017
