version: "3.1"
services:
  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - 8001:1234
    environment:
      - HOST=0.0.0.0
      - DB=mongodb+srv://fmancebo:Deposito.61@cluster0.r7wun.mongodb.net/develop?retryWrites=true&w=majority
    networks:
      - backend

networks:
  backend:
    driver: bridge
